### ISSUE TITLE
Can't run the app

### ISSUE THREAD

**Issue by agcy1210** [martinkooij/MMM-Parcel#10]
Hey I have cloned the repo according to the instructions and I can't run my app using rpm run. Can you explain me a bit more about how to run the app and what we want to do the config code you have mentioned in the repo. As I am new to node so I don't know some stuff and I am working on Python and what to use you take some insights from your project but can't able to run it.

Can you help me out with some more details about setting up the project

**Comment by AndrewSav** [comment]
@agcy1210 you know that this is not a standalone app but a MagicMirror module, right?

**Comment by martinkooij** [comment]
It is a MagicMirror Module, to be used in a larger commuity project abou magicmirrors. Not a standalone version alas. Sorry.
