### ISSUE TITLE
Loading parcel module... issue

### ISSUE THREAD

**Issue by enjoynering** [martinkooij/MMM-Parcel#13]
Hello,

Firstly, thanks for the module, it seems to be amazing.

I have not been able to set up because of the message:

Loading parcel module...

I have copy paste this:

`{
module: 'MMM-Parcel',
position: 'top_right',	// This can be any of the regions. Best results in left or right regions.
header: 'My Parcels',   // This is optional
config: {

	apiKey: 'My api key' // Your free API Key from aftership.com

	}
},`

![Loading](https://user-images.githubusercontent.com/8492492/81736813-70b36900-9497-11ea-948b-42cc73330355.PNG)
![Api](https://user-images.githubusercontent.com/8492492/81736811-701ad280-9497-11ea-9b23-764860900403.PNG)

**Comment by RienduPre** [comment]
I have the same issue?
Any solution found?

**Comment by bertdeelman** [comment]
Hi,

I've got the same issue. Two magic mirrors, two different API keys. At one MM the module is working fine. At the other MM the MMM-Parcel modules is not working. Same error message as above: "Loading parcel module...". 

Any idea how to fix this? Where to search? The API is tested with Postman and at the other MM. 

TypeError: aftershipSDK is not a constructor
    at Class.fetchShipments (/home/pi/MagicMirror/modules/MMM-Parcel/node_helper.js:91:22)
    at Class.startUpdateNext (/home/pi/MagicMirror/modules/MMM-Parcel/node_helper.js:126:8)
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-Parcel/node_helper.js:116:9)
    at Socket.<anonymous> (/home/pi/MagicMirror/js/node_helper.js:112:11)
    at Socket.emit (events.js:200:13)
    at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:82:9)

Regards,
Bert

**Comment by Jsarihan** [comment]
Just got the module and ran into the same bug. Seems like AfterShip updated their sdk so "latest" in package.json won't work. Here's my intermediary fix - I may fork and update to new AfterShip SDK eventually.

**FIX:**
- Go to `modules/MMM-Parcel`
- Update `package.json` dependencies with 
```
"dependencies": {
    "aftership": "5.3.4",
    "google-translate-api": "^2.3.0"
  },
```
- run `npm install` from `modules/MMM-Parcel`
- restart magic mirror

**Comment by Black-Zero** [comment]
Hello,

your intermediary fix solved my problem with "Loading parcel module...", but now I have "No Shipment Data" although I have some shipments listed on AfterShip.

Has anyone a solution for this problem?

Thank you very much!

**Comment by martinkooij** [comment]
Aftership has become a paying API ($199,- / month!!!). I have changed the code to use **Tracktry.com**. That one seems to be free (see Readme.md). Also I cleaned some code.
