### ISSUE TITLE
Status is "undefined"

### ISSUE THREAD

**Issue by MikeBishop** [martinkooij/MMM-Parcel#17]
Packages which were shipped today show `undefined`; appears to be happening in this code:

    var headerStatus = parcelStatustext[parcelStatus.indexOf(p.status)];

...where `p.status` is "InfoReceived".  Since that's not in `parcelStatus`, it fails.  I assume it's equivalent to "pending".

**Comment by martinkooij** [comment]
Merged and moved to "normalize-apiname.js" to offload the complexity of the displaying module and create an abstraction layer between data presented from the API  and the display on the Mirror.
