### ISSUE TITLE
Tracking info not updating

### ISSUE THREAD

**Issue by Cassiano-Gunji** [martinkooij/MMM-Parcel#21]
Greetings, I've started using your module a few days ago and now noticed that the data of my only parcel is not updating. It shows outdated information. The tracking page on Tractry is showing current information.

I tried deleting the parcel info on Tractry and your plugin showed no parcel information. When adding the parcel info on Tractry again, your module started showing the info again, still a few days outdated.

It seems to me this is not an issue of cached data, as it happens with the news module. I suspect there is something wrong with the API. Can you confirm and/or indicate any workaround?

**Comment by martinkooij** [comment]
Ai, It probably does not get the new information from the API. 

It would help if you can start the module with debug: true in the config and send the log files indicating the retreival of the parcel to my private email "martin 'dot' kooij 'dot' 4 'at' gmail 'dot' com".

After a few hours it would be wise to restart with `debug:false` not to clutter the logfiles  too much ;)

Also make a screen print of the tracktry overview. I will try and delve into this over the weekend. I am still struggling with the not so well documented API of Trackrty. 

Thanks for helping it making better together!

Martin

**Comment by martinkooij** [comment]
Repaired. The tracktry API normalization middleware now actively searches for the newest location entry instead of assuming it is on the destination_info part of the result-tree.

**Comment by acmanetas** [comment]
Is it possible that this bug is back? I installed this a few days ago and none of the packages listed are updating, despite there being updates when looking in Tracktry. Thanks in advance!

**Comment by martinkooij** [comment]
mmmm. The Tracktry interface leaves me with surprises all the time. I didn't change the code of late, so the bug is probably similar, but not the same. Can you provide some debug information to me, similar to the one I requested earlier in the thread. It would help me finding the culprit! 

> It would help if you can start the module with debug: true in the MMM-Parcel config and send the log files indicating the retreival of the parcel to my private email "martin 'dot' kooij 'dot' 4 'at' gmail 'dot' com".
> 
> After a few hours it would be wise to restart with `debug:false` not to clutter the logfiles  too much ;)
> 
> Also make a screen print of the tracktry overview. I will try and delve into this over the weekend. I am still struggling with the not so well documented API of Trackrty.

Thanks!
