### ISSUE TITLE
 The delivered packages remain displayed even after having defined a duration.

### ISSUE THREAD

**Issue by 2hdlockness** [martinkooij/MMM-Parcel#23]
Hello
I have defined my config.js as follows:
hideDelivered: 1,
and yet the packages that were delivered 2 or 3 days ago remain displayed on the screen.
<a href="https://ibb.co/SyptN0X"><img src="https://i.ibb.co/6w5HYbR/20210204-103437.jpg" alt="20210204-103437" border="0"></a>
When I set the value to true they are well hidden but I would like it to remain displayed for 1 days.
An idea ?

**Comment by martinkooij** [comment]
Thanks for the find! It seems like the calculation of delivered days is somehow broken. I will try and find out if I can reproduce in a test here at home. If not, I will getwith a request  back to you for more (debug) info.

**Comment by 2hdlockness** [comment]
> Thanks for the find! It seems like the calculation of delivered days is somehow broken. I will try and find out if I can reproduce in a test here at home. If not, I will getwith a request back to you for more (debug) info.

Ok no problem !

**Comment by martinkooij** [comment]
repaired in latest commit on main branch (master). Do a git pull in de ..../modules/MMM-Parcel/ directory. restart MagicMirror and you should be up and running again.

**Comment by 2hdlockness** [comment]
It works Thanks for the modification
