### ISSUE TITLE
TrackTry: Give your Tracking a title

### ISSUE THREAD

**Issue by Black-Zero** [martinkooij/MMM-Parcel#25]
Hello,

I wanted to look for this feature as I found the part inside your description, that it isn't possible yet.
Perhaps you could use the field "Order Number" of TrackTry to Name the deliveries? It's free to fill in everything...

Thank you very much for your effort and support!

Greetings,
Black-Zero

**Comment by martinkooij** [comment]
Done. I followed up on your request/idea in the latest commit on "master". Happy to improve together with the community! 
In ordet to get it working do a "git pull" from your MMM-Parcel directory
