### ISSUE TITLE
Package names aren't unescaped

### ISSUE THREAD

**Issue by MikeBishop** [martinkooij/MMM-Parcel#28]
Enter a package name with an apostrophe, such as "Kohl's". On the MM, it displays as "Kohl\'s".

**Comment by martinkooij** [comment]
Woops, I will go through the code and find the cuplrit(s). Need some "fresh" inputs though for doing a thorough investigation. 

@MikeBishop : Question: in what interface did you enter the title? Current possibilities: MMM_parcel local website, Tracktry shipment website (Order Number now interpreted as title in MMM-Parcel), AfterShip website (title is editable field)?

**Comment by MikeBishop** [comment]
Local site.

**Comment by martinkooij** [comment]
Tracktry internally does a HTML type of escaping before putting it into JSON, and then escaping again into the API result the JSON where necessary. Difficult to fix, all code on MMM-Parcel is correct. So is aftership code and API. 

I thus solved the specific single quote issue in "normalize-trackry.js" part and left the rest for later.
