### ISSUE TITLE
There are no issues

### ISSUE THREAD

**Issue by martinkooij** [martinkooij/MMM-Parcel#7]
Please enter any issues you have, improvement request, or just leave a comment if you are happy!

**Comment by AndrewSav** [comment]
@martinkooij are you still interested? There are a couple of issues there now which are not responed to at all. I also have a suggestion, which I can open as an issue if you are interested.

**Comment by martinkooij** [comment]
Yes, I have been out of the loop for a while,  but picking up my hobby again!

**Comment by sajkhanvict** [comment]
Hi, i have added the module and checked for any errors and it looks like everything is good but the module is stuck on "Loading Parcel module" once everything is loaded on the mirror

Can you please suggest what i should do?

Thank you

**Comment by estradanet** [comment]
> Hi, i have added the module and checked for any errors and it looks like everything is good but the module is stuck on "Loading Parcel module" once everything is loaded on the mirror
> 
> Can you please suggest what i should do?
> 
> Thank you


Hi all,

I have the same "Loading Parcel module" issue.

**Comment by SamBouwer** [comment]
I have the same issue. The AfterShip API might have changed?

**Comment by martinkooij** [comment]
Yes the Aftership API is killed for normal people. Please try the new version 2.0.0 using the Tracktry API. I hope they don't kill this one as well ;(.
