### ISSUE TITLE
autoTranslate

### ISSUE THREAD

**Issue by Rene1709** [martinkooij/MMM-Parcel#8]
Hi Martin,
great stuff so far. Can you tell me how to install the auto translate dependencies?
To be honest I'm new in that area and just started to build my own mirror. Was not able to find it out myself.

Thanks in advance

René

**Comment by martinkooij** [comment]
Hi,

Thanks first for your positive feedback! I am sorry to answer so late, but have been busy!

For having autotranslate you have to install the dependency on the translation api. 

Go into the MMM-Parcel directory and type "npm install".  It should install auto-translate automatically. Or force by hand by typing "npm install google-translate-api"

next add autoTranslate: "xx" to your config.js in the module parameters. That should do the trick for all texts send by the couriers.

If you use "en" you are ready, and all Chinese unreadables from Chinese couriers are changed to English. 

If you have another language, you can also change the parcelStatusText, the onlyDaysFormat, expectedDeliveryText abd the noParcelText to your language. See the Readme at the module's Github for examples. These parameters change the headers and specific  texts. 

If you can't find it, send me your language and I will be glad to help with an example config.js for your language. 

The possible two letter codes for languages can be found at https://cloud.google.com/translate/docs/languages

Let me know how you fare,
Martin Kooij
The Netherlands...

**Comment by martinkooij** [comment]
No more problems? Closed
