### ISSUE TITLE
Track incoming packages

### ISSUE THREAD

**Issue by ryanzor** [martinkooij/MMM-Parcel#9]
Hi, from looking at afterShip it looks like it's primarily meant for managing a wooCommerce site or another situation where I am shipping out a lot of packages.  Is there a good automatic approach to get packages being shipped to me, even if it is just amazon orders it would be neat.

**Comment by AndrewSav** [comment]
@ryanzor I tried this module today, and it seems you can use aftership free plan. They sign you up for 14 days trial to start with, so I'm not sure what happens after that, but they do have the Free tier, that I suppose you get downgraded to after 14 days.

**Comment by tjm7844** [comment]
I think the issue, to @ryanzor's point, is that it's based on shipments, not deliveries.

Is there a way to automatically add deliveries to AfterShip (ie, any time I order anything from Amazon, it's automatically forwarded to my AfterShip for tracking)? Going through and adding tracking numbers manually kind of defeats the purpose.

If not, is there a way to integrate something like UPS MyChoice, which automatically sends me package information if that package gets sent to my address (regardless of who orders it or where it's coming from - as long as it's being delivered through UPS).

The first option would be fine, but I'd much prefer a means to track any parcels being delivered to my address, from any carrier, or any shipper...But I'm not sure the service exists for that yet.

**Comment by MikeBishop** [comment]
The Android app appears to support forwarding tracking e-mails, but there's a disconnect between what's visible in the app and what's visible on the site.  I presume what's visible on the site is what shows up in the API.

**Comment by estradanet** [comment]
> The Android app appears to support forwarding tracking e-mails, but there's a disconnect between what's visible in the app and what's visible on the site. I presume what's visible on the site is what shows up in the API.

I believe, that is because the app is meant for delivery and the site for shipments. Two different approaches for two different clients. I've been fighting with the app because there's too manual work to update it. MMM-Parcel is not working for me but MMM-Aftership is

**Comment by martinkooij** [comment]
You could retry to use MMM-Parcel with Tracktry.com, now that aftership has stopped working. Finally I came around to reserach possibility to update. Sorry for the long long wait. 

I tried to make things easier, the simple config files shoudl work. You maintain the shipments towards you in the my.tracktry.com/shipments dashboard.

**Comment by Black-Zero** [comment]
Thank you very, very much!
I will give it a try the upcoming days!

**Comment by Black-Zero** [comment]
Ok. I couldn't wait for it ^^.

It works for me :)
Thank you very much!

**Comment by martinkooij** [comment]
👍

⁣BlueMail voor Android downloaden ​

Op 18 jan. 2021 21:14, om 21:14, Black-Zero <notifications@github.com> schreef:
